AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

# A top class comment is not needed for this simple gem
Style/Documentation:
  Enabled: false

# 80 chars is really short. Screens got bigger you know.
Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb' # Specs just have large blocks
    - '*.gemspec'    # Is just one block

# We don't support MFA publishing
Gemspec/RequireMFA:
  Enabled: false
