name: CI
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          github_token: ${{ secrets.github_token }}
          reporter: github-check
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - ruby-head
    name: RSpec tests ruby ${{ matrix.ruby }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec spec/rspec
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Run RSpec in GITHUB_WORKSPACE
        run: '! bundle exec rspec spec/integration/failing_spec.rb'
      - name: Run RSpec in sub-directory of GITHUB_WORKSPACE
        run: |
          cd spec/integration
          bundle exec rspec relative_path/pending_spec.rb --require ../spec_helper --format RSpec::Github::Formatter
